### PR TITLE
Change onChange handler to onInput

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by garyb** [comment]
:+1: :+1: :+1:

**Comment by jdegoes** [comment]
The build is failing. Just restarted to see if it was a fluke.

**Comment by jdegoes** [comment]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by puffnfresh** [comment]
@jdegoes there's no tests so it fails.

**Pull request merged**
