### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jonsterling**
I was working on [SD-1408](https://slamdata.atlassian.net/browse/SD-1408), but found that I wanted to rearrange things a little bit before getting deep into the work so that the task would be a bit more manageable.

- Moved the separable aspects of the SlamDown AST into separate modules
- Added `Eq` instances to everything, adjusted the `Eq SlamDown` instance to use these rather than passing through `show`

I figured since the change that we are planning is breaking, now is as good a time as any to revamp the module structure.

### CODE REVIEW

**Comment by jonsterling** [comment]
Does anyone (@garyb or @beckyconning or @cryogenian) have a moment to look these changes over? They are mostly cosmetic, aside from the `Eq` instances.

**Comment by garyb** [comment]
Sure thing

**Comment by garyb** [comment]
Looks good to me! :+1:

**Comment by jonsterling** [comment]
@garyb thanks!

**Pull request merged**
