### PR TITLE
Updates for Halogen 0.4

### PR DESCRIPTION
**Pull request by paf31**
@jdegoes Could you please review?

This tidies things up quite a lot, and I think we can make a release now.

I can spend some time speeding this up now, replacing things like `[]` with `List`, if you like.

Thanks.

### CODE REVIEW

**Comment by jdegoes** [comment]
CI build failed, but otherwise looks good! We should open a ticket to improve performance. The other project we need ported to Halogen is purescript-jtable, which probably has higher priority than improving the performance of this one.

**Comment by paf31** [comment]
Looks like a Bower issue due to old deps in strongcheck. Let's see what happens this time.

**Comment by paf31** [comment]
I'm not sure what's wrong now. I see `spawn ENOENT` from `gulp` in the logs during the `psc-docs` step.

@garyb Any ideas?

**Comment by garyb** [comment]
I'm not sure, and without using `gulp-plumber` there's probably no way of telling where that's coming from.

**Pull request merged**
