### PR TITLE
Implement the spec

### PR DESCRIPTION
**Pull request by paf31**
This pull request aims to satisfy the requirements of the specification:

- Support for a subset of the CommonMark spec, including block and inline elements, lists and blockquotes (modulo certain simplifications)
- Inline form fields
- Evaluation of embedded code, via traversals (implemented using the `everywhere` function)

The test suite tests that the pretty printer and parser are compatible for a representative set of documents.

In addition, there is a HTML renderer provided, as well as an example application which converts markdown to HTML in realtime. This should also provide the ability to perform ad-hoc tests.

The implementation is somewhat naive, and performance can certainly be improved for large documents.

Some of the code is loosely based on [cheapskate](https://github.com/jgm/cheapskate), hence the update to the LICENSE file.

@jdegoes, please let me know what you think.

### CODE REVIEW

**Comment by jdegoes** [comment]
@paf31 This looks great! So glad this project finally made some progress after all these months.

I only have two comments:

1. Can we get the old README back in there, updated to reflect changes to the API? It has some docs that some might find useful, especially with regards to range of CommonMark support, and the extensions to CommonMark.
2. Can we get a strongcheck test to verify that `prettyPrintMd >>> parseMd` is an identity for an `Arbitrary` `SlamDown` document?

**Comment by paf31** [comment]
I can definitely work on those things. I started on a strongcheck test suite, and got pretty far, but I ran into a problem of generating invalid documents (the parser collapses many `Str`s into one, for example). I think that by restricting the generator to certain classes of document, I can come up with some meaningful tests.

**Comment by jdegoes** [comment]
That makes sense. The other option would be to add a `canonicalize` function to canonicalize a SlamDown document before equality comparison. Not sure which one would be easier.

Thanks again for your awesome work on this, look forward to merging the PR soon. :smile:

**Comment by paf31** [comment]
Ok, the README is back, and updated. I'll work on the tests later tonight, and hopefully have something useful to show.

I suspect there may be some failing corner cases which the tests will expose, so there may be some bug fixes as well, and I might restrict the generator to avoid any particularly nasty cases (in the spirit of getting the 95% use case working first).

**Comment by jdegoes** [comment]
Sounds good, look forward to seeing it!

**Comment by paf31** [comment]
@jdegoes I've added a StrongCheck test suite, and fixed a couple of minor bugs.

I just noticed after checking the spec, that I'm currently missing link references, so I'll add a parser for those now.

I'm also aware of one other minor bug, which I'd like to fix.

Please let me know what you think.

**Comment by paf31** [comment]
@jdegoes There is now basic support for link references and reference links in the following form:

```
[Label][ref]

   [ref]: /link/to/resource
```

I think this completes all of the features in the spec, at least in some form or another. There are still plenty of corner cases which we could work on later, as well as performance improvements.

**Comment by jdegoes** [comment]
Thanks, @paf31, this is great work! Merged, and I'll intro you to Jeff this morning.

**Pull request merged**
