### PR TITLE
[SD-1405] Document multiple-tick delimiters

### PR DESCRIPTION
**Pull request by jonsterling**

### CODE REVIEW

**Comment by garyb** [comment]
It's a slightly difficult sentence to parse, but I also can't think of any way of improving it! Perhaps we could add an example to illustrate?

**Comment by jonsterling** [comment]
@garyb Yes, I had trouble both writing and reading it :wink: 

I'll at least add an example, but also see if I can come up with a way to make the sentence clearer.

**Comment by jonsterling** [comment]
OK, I added an example; I can't really think of a way to rephrase that sentence, but I'm open to suggestions from anyone.

**Comment by garyb** [comment]
:back: :heavy_check_mark: (:+1:)

**Pull request merged**
