### PR TITLE
Use purescript-halogen

### PR DESCRIPTION
**Pull request by paf31**
@jdegoes This isn't quite ready yet, and will probably need a versioned, updated release of Halogen, but should be a start towards https://github.com/slamdata/purescript-halogen/issues/36.

### CODE REVIEW

**Comment by jdegoes** [comment]
Travis failed, otherwise looks good! :+1:

**Comment by paf31** [comment]
@jdegoes This should be good to go when we can fix the halogen dependency in the `bower.json` file. That should fix the Travis issue too.

How does the code look?

**Comment by jdegoes** [comment]
:shipit: 

What exactly do we need to fix in Halogen to get Travis working here?

**Comment by paf31** [comment]
We just need a versioned release to stick in the Bower file. Travis is complaining about resolving `github.com` if you look in the log.

**Comment by jdegoes** [comment]
We have 0.3.0, but I guess that’s not new enough for this?


-- 
John A. De Goes
Follow me @jdegoes

On April 2, 2015 at 10:37:30 AM, Phil Freeman (notifications@github.com) wrote:

We just need a versioned release to stick in the Bower file. Travis is complaining about resolving github.com if you look in the log.

**Comment by paf31** [comment]
Right, I think once 0.4 is done, we can bump the dependency here and it should work.

**Pull request merged**
