### PR TITLE
Switch to more reliable travis build; switch to pulp

### PR DESCRIPTION
**Pull request by jonsterling**
- The `trusty` image has more juice apparently; switching to this results in a much faster, more reliable build, and seems to solve the problem where about 90% of the time, `psc` reports no output for more than 10 minutes.

- Use `pulp` instead of `gulp`, since `pulp` is easier and it doesn't appear that we're getting anything special from `gulp` at this point.

### CODE REVIEW

**Comment by cryogenian** [comment]
Is `sudo: required` needed to make build fast?

**Comment by jonsterling** [comment]
@cryogenian Yes, [apparently](https://docs.travis-ci.com/user/trusty-ci-environment/)... I have no idea why, but I tried it without `sudo: required`, and the build was just as slow as before.

**Comment by cryogenian** [comment]
:+1:

**Comment by jonsterling** [comment]
@cryogenian thanks!

**Pull request merged**
